# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='secondary',
            field=models.ManyToManyField(blank=True, related_name='secondary_category', to='categories.Category'),
        ),
    ]
