# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lecture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='lecture',
            name='free',
            field=models.BooleanField(default=False),
        ),
    ]
