# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
